################################################################################
#SCRIPT TO COMPILE CLOUD VOLUME DATA  
#please contact Holly Roach at hmroach@hotmail.co.uk if you have any questions
################################################################################
#OUTPUTS: New_Line_Name_Cloud_Volume_Compile.csv 
#compiles all the cloud volume data, that was generated by ImageJ macro, into one table
#IMPORTANT to make sure you have ran the ImageJ macro (ImageJ_Cloud_Volume.ijm) prior to running this script
# --> this macro calculates the cloud volume for each cropped cloud per time-point for each phase and dataset
#makes sure tidyverse, stringr and tcltk packaged have been installed - install.packages("package_name")

#load libraries
library(tidyverse)
library(stringr)
library(tcltk)

#create function to replace choose.dir so that it is compatible with mac OS
choose_dir <- function(caption = 'Select data directory') {
  if (exists('utils::choose.dir')) {
    choose.dir(caption = caption)
  } else {
    tk_choose.dir(caption = caption)
  }
}

################################################################################
#USER INPUT REQUIRED

#set name of new cell line - should be spelled the same as folder name within the directory
#make sure not to use any spaces or symbols other than an underscore (_), dash (-), or full stop (.)
#eg "Mettl3_dTAG" or "SPEN_RRM_del" or "Ciz1_KO"
New_Line_Name <- "Test"           

#define type of cells used in experiment - either "mESCs" or "NPCs"
Cell_Type <- "mESCs"


################################################################################
#OTHER INPUTS
#the below inputs should not need changing

#creates list of datasets being used for compile
Data_Set_List <- c("nascent_Xist_dynamics",
                   "Xist_turnover_on_chromatin")

#define file path to where "Pulse_Chase_Analysis" is located - results from ImageJ_Cloud_Volume.ijm are stored
File_Path <- choose_dir(caption = "Select Pulse_Chase_Analysis folder, where compiled data will be stored")


################################################################################
#VALIDATE INPUTS

#checks inputted name of new cell line - compares name to REGEX
if (grepl("\\W", New_Line_Name)) {
  stop(paste("Invalid character in name of new cell line (", New_Line_Name, " - New_Line_Name) - must not contain any spaces or symbols", sep=""))
}

#checks name of dataset
if (!("nascent_Xist_dynamics" %in% Data_Set_List |"Xist_turnover_on_chromatin" %in% Data_Set_List)) {
  stop("Invalid names entered in Data_Set_List - must contain either
       nascent_Xist_dynamics or Xist_turnover_on_chromatin or both")
}

#checks name of cell type
if (!(Cell_Type == "mESCs" | Cell_Type == "NPCs")) {
  stop("Invalid name entered in Cell_Type - must be mESCs or NPCs")
}

#checks correct folder has been selected for file path
if (!(str_sub(File_Path, -20, -1) == "Pulse_Chase_Analysis")) {
  stop("Pulse_Chase_Analysis folder not selected for File_Path")
}


#checks that user has permissions to read and write files in Pulse_Chase_Analysis folder
if (!(file.access(File_Path, 2) == 0 && file.access(File_Path, 4) == 0 )) {
  stop("Invalid file permissions for Pulse_Chase_Analysis folder - check in folders properties that you have permission to read&write")
}

#checks that Pulse_Chase_Analysis folder contains folder for new cell line
if (!dir.exists(paste(Output_File_Path, Cell_Type, "Cloud_Volume", New_Line_Name, sep="/"))) {
  stop(paste("Folder for the new cell line (", New_Line_Name, " - New_Line_Name) does not exist in Pulse_Chase_Analysis folder", sep=""))
}

#checks that Pulse_Chase_Analysis folder contains subfolders for either dataset for new cell line
if (!dir.exists(paste(Output_File_Path, Cell_Type, "Cloud_Volume", New_Line_Name, "nascent_Xist_dynamics", sep="/")) 
    || !dir.exists(paste(Output_File_Path, Cell_Type, "Cloud_Volume", New_Line_Name, "Xist_turnover_on_chromatin", sep="/"))
) {
  stop(paste("nascent_Xist_dynamics or Xist_turnover_on_chromatin subfolders do not exits for new cell line (", New_Line_Name, " - New_Line_Name) within the Pulse_Chase_Analysis folder", sep=""))
}

#checks that Pulse_Chase_Analysis folder contains subfolders for Individual_Timepoints for either dataset for new cell line
if (!dir.exists(paste(Output_File_Path, Cell_Type, "Cloud_Volume", New_Line_Name, "nascent_Xist_dynamics", "Individual_Time_Points", sep="/")) 
    || !dir.exists(paste(Output_File_Path, Cell_Type, "Cloud_Volume", New_Line_Name, "Xist_turnover_on_chromatin", "Individual_Time_Points", sep="/"))
) {
  stop(paste("nascent_Xist_dynamics or Xist_turnover_on_chromatin subfolders do not contain the Individual_Time_Points folder for new cell line (", New_Line_Name, " - New_Line_Name) within the Pulse_Chase_Analysis folder", sep=""))
}



################################################################################
#creates table which will store table for new cell line data

New_Cell_Line <- tibble(Cell_Line = character(),
                        Data_Set = character(), 
                        Phase = character(), 
                        Time = numeric(),
                        Cloud_Name = character(),
                        Cloud_Volume = numeric())


################################################################################
#loops through all the datasets to collect all the cloud volume tables for each time point

for (Data_Set in Data_Set_List) {
  
  #based on data set being used - defines name of the data
  if (Data_Set == "nascent_Xist_dynamics") {
    Data_Name <- "Dynamic"
  } else {
    Data_Name <- "Turnover"
  }

  #set file path to the location of the Cloud_Volume files 
  Input_Path <- paste(File_Path, Cell_Type, "Cloud_Volume", New_Line_Name, Data_Set, "Individual_Time_Points", sep="/")

  #stores name of all Cloud_Volume files, in the directory, into a vector
  Volume_Files <- list.files(path = Input_Path, pattern = "0.*csv", full.names  = TRUE)   #all Cloud_Volume files end in a 0
  
    #creates a list containing the Cloud_Volume tibble files
  Volume_List <- lapply(Volume_Files, read_csv)
  
  #concatenates all the individual Cloud_Volume tibbles into 1 tibble
  Phases_Complie <- bind_rows(Volume_List) %>%
    transmute(Cell_Line = New_Line_Name,
              Data_Set = Data_Name, 
              Phase = Phase, 
              Time = Time,
              Cloud_Name = str_extract(Image_Name, r"(\d{0,2}_Cloud\-\d{1,3})"), 
              Cloud_Volume = Volume)
  
  New_Cell_Line <- bind_rows(New_Cell_Line, Phases_Complie)
  
}


################################################################################
#save tables

#if folder for new cell line does not exit, create folder to save density data
save_path <- paste(File_Path, Cell_Type, "Cloud_Volume", New_Line_Name, sep="/")

#define file path to location of data for all other cell lines
Other_Data_Path <- paste(File_Path, Cell_Type, "Cloud_Volume", "All_Cell_Lines", sep="/")

#save data in both locations
File_Name <- paste(New_Line_Name, "Cloud_Volume_Compile.csv", sep="_")

write_csv(New_Cell_Line, paste(save_path, File_Name, sep="/"))
write_csv(New_Cell_Line, paste(Other_Data_Path, File_Name, sep="/"))